### ISSUE TITLE
Arenavision plugin

### ISSUE THREAD

**Issue by WolfganP** [AndreyPavlenko/aceproxy#22]
Hi, FOA, thanks for keeping this project alive.
I was trying to get my shot at writing a plugin for http://arenavision.in/ and wanted to get some advice in advance (ie which of the existing plugins to use as base for my one).

The site maintains a running schedule at http://arenavision.in/schedule but the actual links aren't in list form anywhere, but every channel page (ie http://arenavision.in/av11) has to be scraped to get the acestream:// link.

Any suggestions? Thanks!

**Comment by AndreyPavlenko** [comment]
Hi,

You may use the allfon plugin as an example, it is quite simple.
All you need is to implement the handle() method which generates the
playlist.

In this method you need to create PlaylistGenerator and add playlist items
to this list:

        playlistgen =
PlaylistGenerator(m3uchanneltemplate=config.m3uchanneltemplate)
        for match in matches:
            playlistgen.addItem(match.groupdict())
