### ISSUE TITLE
Перемотка для торрентов

### ISSUE THREAD

**Issue by pro777s** [AndreyPavlenko/aceproxy#23]
Здравствуйте, Андрей,
Спасибо за Ваш труд. AceProxy стабильно работает. 
В AceProxy реализована отличная возможность смотреть торрент-фильмы без скачивания. 
Но неудобство представляет отсутствие возможности перемотки. Будет ли это сделано?
Такую возможность сделал [Валерий Кадышев](http://blog.sci-smart.ru/2016/01/acephproxy-064.html) на PHP. Здесь его проект на [GitHub](https://github.com/mexxval/AcePHProxy) На удивление его прокси довольно-таки стабильно работает: мало разрывов, возможность смотреть "тяжелые" торренты благодаря им реализованному буферу и логике его обработки. Может быть, воспользоваться его наработками?

**Comment by AndreyPavlenko** [comment]
Здравствуйте,
Это давно есть в планах, но, к сожалению, не хватает свободного времени для реализации.
