### ISSUE TITLE
Загрузка torrent-telik плейлиста отдает 500у ошибку

### ISSUE THREAD

**Issue by mihdan** [AndreyPavlenko/aceproxy#28]
Это связано со смертью torrent-telik.com? Нет альтернативы?

**Comment by privatesam** [comment]
Yes this is the problem.  I wonder if there is a workaround - those channels are still out there.

**Comment by mihdan** [comment]
@AndreyPavlenko вы бы ответили, прежде чем тикек закрыть )

**Comment by AndreyPavlenko** [comment]
Выше ведь ответили. Лично я не знаю в чем причина, я этим плагином не пользуюсь.

**Comment by mihdan** [comment]
Понятно

пт, 13 окт. 2017 г., 1:07 Andrey <notifications@github.com>:
