### ISSUE TITLE
How to pull new changes from git?

### ISSUE THREAD

**Issue by sei4eto** [AndreyPavlenko/aceproxy#30]
Hello!
It is a dummy question but I'd like to ask how can I pull new changes from git to my computer?
I used "git pull command" but it returns error "you need to stash you changes torrenttv plugin". I did quick search but cannot find any useful information. I tried to remove torrenttv plugin and then execute git pull. Aceproxy was successfully update but when I tried to start it from acehttp it dosn't start.
Thank you!

**Comment by AndreyPavlenko** [comment]
Use rm -rf + git clone unless you know how to stash and restore.
Hope this helps - https://git-scm.com/book/en/v2
