### ISSUE TITLE
HLS and AceProxy

### ISSUE THREAD

**Issue by MajorChump** [AndreyPavlenko/aceproxy#31]
How do we use aceproxy to HLS. Acestream ".m3u8 & .ts" generation is simple through the http api they have but doesn't allow multiple separate streams to be watched. It stops one if another is loaded.

I believe that can be solved by aceproxy and VLC? Problem is I have a acestream content id (CID) and I can't see how I would generate .m3u8 and .ts as its limited to certain file types when using /pid/. Am I missing something simple?

Is there a simple URL that can be used like: 

IP:PORT/pid/CID/stream.m3u8

**Comment by AndreyPavlenko** [comment]
HLS is not supported by AceProxy.

**Comment by MajorChump** [comment]
I see, is there a technical reason why it isnt?

Also do you know of anyway to allow acestreamengine to stream multiple without stopping one for another?

**Comment by AndreyPavlenko** [comment]
It doesn't make sense.
Acestream from this repository supports multiple clients.

**Comment by MajorChump** [comment]
Something to do with http://wiki.acestream.org/wiki/index.php/Engine_HTTP_API#Player_ID

Player ID purpose - app engine should distinguish one player from another, as in the current engine implementation user cannot play the same live-stream with two (or more) players from one engine, and engine will stop to serve requests from one player, when got a new request from another.
