### ISSUE TITLE
Dont auto delete the old segments

### ISSUE THREAD

**Issue by nickcarterney** [AndreyPavlenko/aceproxy#33]
Hi,

I'm using Ace Proxy to restreaming torrent TV, and getting a issue: the old segments in the temp folder is not deleted. I got fulldisk error after 1 day

Hope you have any plan to fix it :)

Thanks!

**Comment by AndreyPavlenko** [comment]
Hi,
What are the "old segments"?

**Comment by nickcarterney** [comment]
The files are generated in the Ace's temp folder :D

**Comment by AndreyPavlenko** [comment]
I suppose you are talking about the ace stream engine cache folder. This folder is not created by the proxy. You need to configure the engine's cache size. Please read acestreamengine --help.
I would recommend to use the inmemory cache -  --live-cache-type memory.
